//! Tough retrieval test: ALL data generated by LLM with adversarial noise
//!
//! Uses the LLM to dynamically generate everything:
//! - 1 golden fact session (the retrieval target)
//! - ~15 adversarial noise sessions (share keywords with golden fact)
//! - ~45 clean noise sessions (completely unrelated topics)
//! - Positive queries (direct + indirect, targeting golden fact)
//! - Negative queries (targeting specific noise sessions)
//!
//! Tests retrieval with K=5 against 60+ memories (~8% retrieval rate).
//!
//! Run: `cargo tough-tests`

#![cfg(feature = "local")]

use std::sync::Arc;
use std::time::Instant;

use llm_mem::{
    Config, config::MemoryConfig, VectorStore,
    llm::{LLMClient, client::extract_json_from_text},
    memory::MemoryManager,
    types::{Filters, LayerInfo, Memory, MemoryMetadata},
};
use tempfile::TempDir;

mod tough_pipeline {
    use super::*;

    struct NoisySession {
        topic: String,
        session: String,
        is_adversarial: bool,
    }

    // ── LLM generation helpers ──

    async fn generate_golden_fact(client: &dyn LLMClient) -> String {
        let prompt = concat!(
            "Create ONE realistic chat session containing a specific factual statement. ",
            "Must include: a person's name, specific date (month and year), monetary amount, ",
            "city name, and a specific event or action.\n\n",
            "Write as natural chat between [User] and [Assistant], 2-3 exchanges, 150-250 words.\n\n",
            "Return ONLY valid JSON, no markdown fences:\n",
            "{\"session\": \"--- Session ---\\nDate: ...\\n[User]: ...\\n[Assistant]: ...\"}"
        );

        for attempt in 1..=3 {
            match client.complete(prompt).await {
                Ok(response) => {
                    if let Some(json_str) = extract_json_from_text(&response) {
                        let repaired =
                            jsonrepair::repair_json(&json_str, &jsonrepair::Options::default())
                                .unwrap_or(json_str);
                        #[derive(serde::Deserialize)]
                        struct S {
                            session: String,
                        }
                        if let Ok(parsed) = serde_json::from_str::<S>(&repaired) {
                            if parsed.session.len() > 100 {
                                return parsed.session;
                            }
                        }
                    }
                }
                Err(e) => eprintln!("  [golden] attempt {} LLM error: {}", attempt, e),
            }
            eprintln!("  [golden] attempt {} parse failed, retrying...", attempt);
        }
        panic!("Failed to generate golden fact after 3 attempts");
    }

    async fn generate_noise_batch(
        client: &dyn LLMClient,
        golden_session: &str,
        topics: &[&str],
        adversarial: bool,
    ) -> Vec<NoisySession> {
        let adversarial_note = if adversarial {
            "CRITICAL: Each session MUST share some SURFACE KEYWORDS with the golden fact \
             (similar names, same city, similar dates, similar dollar amounts, related topics) \
             but MUST NOT contain the actual golden fact. The goal is to create sessions that \
             LOOK SIMILAR to search embeddings but are about different events."
        } else {
            "Each session should be completely unrelated to the golden fact. \
             Use diverse everyday topics with no keyword overlap."
        };

        let topic_list: String = topics
            .iter()
            .enumerate()
            .map(|(i, t)| format!("{}. {}", i + 1, t))
            .collect::<Vec<_>>()
            .join("\n");

        let prompt = format!(
            concat!(
                "GOLDEN SESSION (for reference):\n{}\n\n",
                "{adversarial_note}\n\n",
                "Generate {} short chat sessions about these topics:\n{topic_list}\n\n",
                "Format each session EXACTLY like this, separated by ===:\n",
                "TOPIC: topic_name\n",
                "SESSION: --- Session ---\nDate: YYYY-MM-DD\n[User]: ...\n[Assistant]: ...\nEND\n",
                "===\n",
                "TOPIC: topic_name\n",
                "SESSION: --- Session ---\nDate: YYYY-MM-DD\n[User]: ...\n[Assistant]: ...\nEND\n",
                "===\n\n",
                "Each session: 2-3 exchanges, ~100 words. Return ONLY the formatted sessions."
            ),
            golden_session,
            topics.len(),
            adversarial_note = adversarial_note,
            topic_list = topic_list
        );

        let mut results = Vec::new();
        for attempt in 1..=2 {
            match client.complete(&prompt).await {
                Ok(response) => {
                    // Strategy 1: Try === delimited blocks with TOPIC: prefix
                    for block in response.split("===") {
                        let block = block.trim();
                        if block.len() < 30 {
                            continue;
                        }

                        let topic = block
                            .lines()
                            .find(|l| l.starts_with("TOPIC:"))
                            .map(|l| l["TOPIC:".len()..].trim().to_string())
                            .unwrap_or_else(|| "unknown".to_string());

                        let session_lines: Vec<String> = block
                            .lines()
                            .skip_while(|l| !l.contains("Session"))
                            .skip(1)
                            .take_while(|l| !l.trim().eq_ignore_ascii_case("END"))
                            .map(|l| l.to_string())
                            .collect();

                        if session_lines.len() >= 2 {
                            let session_text = format!("--- Session ---\n{}", session_lines.join("\n"));
                            if session_text.len() > 50 {
                                results.push(NoisySession {
                                    topic,
                                    session: session_text,
                                    is_adversarial: adversarial,
                                });
                            }
                        }
                    }

                    // Strategy 2: If strategy 1 failed, try splitting on "--- Session ---"
                    if results.is_empty() {
                        for block in response.split("--- Session ---") {
                            let block = block.trim();
                            if block.len() < 50 {
                                continue;
                            }

                            let topic = block
                                .lines()
                                .find(|l| l.starts_with("TOPIC:"))
                                .map(|l| l["TOPIC:".len()..].trim().to_string())
                                .unwrap_or_else(|| "unknown".to_string());

                            let session_text = format!("--- Session ---\n{}", block);
                            if session_text.len() > 50 {
                                results.push(NoisySession {
                                    topic,
                                    session: session_text,
                                    is_adversarial: adversarial,
                                });
                            }
                        }
                    }

                    // Strategy 3: If both failed, try splitting on "Date:" lines
                    if results.is_empty() {
                        for block in response.split("Date:") {
                            let block = block.trim();
                            if block.len() < 50 || !block.contains("[User]") {
                                continue;
                            }

                            let topic = "unknown".to_string();
                            let session_text = format!("--- Session ---\nDate:{}", block);
                            results.push(NoisySession {
                                topic,
                                session: session_text,
                                is_adversarial: adversarial,
                            });
                        }
                    }

                    if results.len() >= topics.len() / 3 {
                        return results;
                    }
                    results.clear();
                }
                Err(e) => eprintln!("  [noise] attempt {} LLM error: {}", attempt, e),
            }
        }
        results
    }

    async fn generate_queries(
        client: &dyn LLMClient,
        golden: &str,
        noise_topics: &[String],
    ) -> (Vec<String>, Vec<String>) {
        // Pick 3 specific clean noise topics for negative queries
        let neg_topic_pool: Vec<&String> = noise_topics
            .iter()
            .filter(|t| {
                let lower = t.to_lowercase();
                !lower.contains("same") && !lower.contains("similar")
                    && !lower.contains("different")
            })
            .collect();
        let neg_topics: Vec<&String> = neg_topic_pool
            .iter()
            .rev()
            .take(3)
            .rev()
            .copied()
            .collect();
        let neg_topics_str: String = neg_topics.iter().enumerate().map(|(i, t)| {
            format!("  {}. {}", i + 1, t)
        }).collect::<Vec<_>>().join("\n");

        let prompt = format!(
            concat!(
                "GOLDEN FACT SESSION:\n{}\n\n",
                "Generate retrieval queries.\n\n",
                "Return ONLY valid JSON, no markdown:\n",
                "{{\"positive\": [\"q1\", \"q2\", \"q3\"], ",
                "\"negative\": [\"q1\", \"q2\", \"q3\"]}}\n\n",
                "POSITIVE queries (3 total):\n",
                "  - Must ask about SPECIFIC, UNIQUE details from the golden fact above.\n",
                "  - Include exact names, dates, amounts, locations from the golden fact.\n",
                "  - Example: \"What amount did [NAME] get from [EVENT] on [DATE] in [CITY]?\"\n\n",
                "NEGATIVE queries (3 total):\n",
                "  - Each query MUST be about ONE of these unrelated topics:\n",
                "{}\n",
                "  - Each query must NOT mention any names, dates, amounts, or locations from the golden fact.\n",
                "  - Each query must NOT be about grants, awards, achievements, or financial events.\n",
                "  - Example for \"cooking recipes\": \"What ingredients do I need for a good pasta dish?\"\n",
                "  - Example for \"travel planning\": \"What are the best hotels in Tokyo for a weekend trip?\"\n"
            ),
            golden, neg_topics_str
        );

        for attempt in 1..=3 {
            match client.complete(&prompt).await {
                Ok(response) => {
                    if let Some(json_str) = extract_json_from_text(&response) {
                        let repaired =
                            jsonrepair::repair_json(&json_str, &jsonrepair::Options::default())
                                .unwrap_or(json_str);
                        #[derive(serde::Deserialize)]
                        struct Q {
                            positive: Vec<String>,
                            negative: Vec<String>,
                        }
                        if let Ok(parsed) = serde_json::from_str::<Q>(&repaired) {
                            if parsed.positive.len() >= 2 && parsed.negative.len() >= 2 {
                                return (parsed.positive, parsed.negative);
                            }
                        }
                    }
                }
                Err(e) => eprintln!("  [queries] attempt {} LLM error: {}", attempt, e),
            }
            eprintln!("  [queries] attempt {} parse failed, retrying...", attempt);
        }
        panic!("Failed to generate queries after 3 attempts");
    }

    // ── Storage helpers ──

    async fn store_session(
        mgr: &MemoryManager,
        client: &dyn LLMClient,
        content: &str,
    ) -> String {
        let embedding = client.embed(content).await.expect("embed failed");
        let meta = MemoryMetadata::new()
            .with_layer(LayerInfo::custom(0, "raw_content"));
        let mem = Memory::with_content(content.to_string(), embedding, meta);
        mgr.store_memory(mem).await.expect("store_memory failed")
    }

    async fn make_manager(
        temp_dir: &TempDir,
        client: Box<dyn LLMClient>,
    ) -> MemoryManager {
        let dim = 384;
        let config = llm_mem::lance_store::LanceDBConfig {
            table_name: "tough_test".into(),
            database_path: temp_dir.path().to_path_buf(),
            embedding_dimension: dim,
        };
        let store: Box<dyn VectorStore> = Box::new(
            llm_mem::lance_store::LanceDBStore::new(config)
                .await
                .unwrap(),
        );
        let mem_cfg = MemoryConfig {
            max_memories: 1000,
            similarity_threshold: 0.65,
            max_search_results: 50,
            auto_enhance: false,
            deduplicate: false,
            merge_threshold: 0.75,
            auto_summary_threshold: 32768,
            max_content_length: 32768,
            document_chunk_size: 2000,
            memory_ttl_hours: None,
            search_similarity_threshold: Some(0.0),
            use_llm_query_classification: false,
            llm_format_detection: false,
            llm_fallback_parsing: false,
            chunk_threshold_chars: 2500,
        chunk_size_chars: 1000,
        chunk_overlap_chars: 100,
        max_cascade_fanout: 5000,
        raw_content_scan_limit: 5000,
        max_list_limit: 10000,
        max_total_candidates: 10000,
        auto_link_threshold: 0.75,
        auto_link_max_relations: 10,
        };
        MemoryManager::new(store, client, mem_cfg, None, llm_mem::memory::metrics::LlmBackendType::Local)
    }

    // ── Main test ──

    /// End-to-end retrieval test with ALL LLM-generated data.
    ///
    /// The LLM generates: 1 golden fact + ~40 adversarial noise + ~120 clean noise + queries.
    /// Tests K=5 retrieval against 160+ memories (~3% retrieval rate).
    /// Adversarial noise shares keywords with the golden fact to create real discrimination.
    #[serial_test::serial]
    #[tokio::test]
    async fn tough_llm_generated_retrieval() {
        let start = Instant::now();

        println!("\n  ═══ Tough Retrieval: All LLM-Generated Data ═══\n");

        // ── Phase 0: Setup LLM client ──
        println!("  Phase 0: Creating LLM client...");
        let mut config = Config::default();
        config.apply_env_overrides();
        if config.llm.cpu_threads <= 0 {
            config.llm.cpu_threads = std::thread::available_parallelism()
                .map(|n| n.get() as i32)
                .unwrap_or(8);
        }
        if config.llm.gpu_layers == 0 {
            config.llm.gpu_layers = 999;
        }

        let client: Box<dyn LLMClient> =
            match llm_mem::llm::create_llm_client(&config).await {
                Ok(c) => match c.health_check().await {
                    Ok(true) => {
                        let s = c.get_status();
                        println!(
                            "  ✓ LLM: {} | Embedding: {}",
                            s.llm_model, s.embedding_model
                        );
                        c
                    }
                    _ => {
                        println!("  ✗ Health check failed");
                        return;
                    }
                },
                Err(e) => {
                    println!("  ✗ Cannot create client: {}", e);
                    return;
                }
            };

        let gen_client = dyn_clone::clone_box(client.as_ref());

        // ── Phase 1: Generate golden fact (1 LLM call) ──
        println!("\n  Phase 1: Generating golden fact (1 LLM call)...");
        let golden_session = generate_golden_fact(&*gen_client).await;
        let golden_preview: String = golden_session.chars().take(100).collect();
        println!("  ✓ Golden: {}...", golden_preview);

        // ── Phase 2: Generate adversarial noise (40 sessions, 4 batches) ──
        println!("\n  Phase 2: Generating adversarial noise (shares keywords with golden fact)...");
        let adv_topics = vec![
            "same person different event", "same city different person",
            "same amount different event", "same date different event",
            "similar person name different event", "same city same amount different event",
            "same person same date different city", "same event type different details",
            "same person different amount", "same city similar date",
            "similar name similar amount", "same person same city different year",
            "same event different outcome", "same person different action",
            "same city same person different topic", "same person same amount different city",
            "same date same city different person", "similar name same date different event",
            "same person different year same city", "same amount same person different event",
            "same city similar person similar amount", "same event type same city different person",
            "same person same month different year", "similar name same city same event type",
            "same amount same city different person", "same person different amount same city",
            "same date similar person different event", "same city same year different event",
            "same person same topic different outcome", "similar name similar date similar amount",
            "same event different person same city", "same person different city same amount",
            "same date different person similar event", "same city same amount different year",
            "same person same city different topic", "similar name same amount different city",
            "same event type similar person same city", "same person different date similar amount",
            "same city same person different outcome", "same amount similar person same date",
        ];
        let adv_batches = 4;
        let mut all_noisy: Vec<NoisySession> = Vec::new();
        for b in 0..adv_batches {
            let chunk_start = b * (adv_topics.len() / adv_batches);
            let chunk_end = if b == adv_batches - 1 { adv_topics.len() } else { (b + 1) * (adv_topics.len() / adv_batches) };
            let chunk = &adv_topics[chunk_start..chunk_end];
            print!("    Batch {} ({}/{})...", b + 1, chunk.len(), adv_topics.len());
            let batch = generate_noise_batch(&*gen_client, &golden_session, chunk, true).await;
            let count = batch.len();
            all_noisy.extend(batch);
            println!(" ✓ ({})", count);
        }
        println!("  Adversarial sessions: {}", all_noisy.iter().filter(|s| s.is_adversarial).count());

        // ── Phase 3: Generate clean noise (80 sessions, 4 batches) ──
        println!("\n  Phase 3: Generating clean noise (unrelated topics)...");
        let clean_topics = vec![
            "cooking recipes", "travel planning", "home repair", "pet care", "fitness routine",
            "book recommendations", "garden planting", "car maintenance", "stock market basics",
            "language learning", "photography tips", "movie reviews", "music production",
            "hiking trails", "coffee brewing", "yoga practice", "baking bread", "cycling routes",
            "meditation", "woodworking", "bird watching", "fishing tips", "camping gear",
            "astronomy", "pottery making", "dance classes", "chess strategy", "origami",
            "volunteering", "budgeting", "meal prep", "plant care", "school project",
            "remote work tips", "video editing", "board games", "knitting patterns",
            "calligraphy", "tea tasting", "rock climbing", "beekeeping", "composting",
            "watercolor painting", "guitar chords", "sushi making", "home automation",
            "crossword puzzles", "sailing basics", "scrapbooking", "fencing sport",
            "carpentry basics", "dance choreography", "trail running", "bird feeding",
            "astrophotography", "sourdough starter", "home gardening", "podcast recording",
            "dog training", "wine tasting", "sneaker collecting", "interior design",
            "smartphone photography", "meal planning", "sleep hygiene", "time management",
            "public speaking", "email productivity", "desk organization", "office ergonomics",
            "weekend projects", "neighborhood events", "community service", "charity work",
            "book club", "writing journal", "art therapy", "mindfulness app", "habit tracking",
            "goal setting", "journaling prompts", "morning routine", "evening wind down",
            "self care tips", "stress management", "anxiety coping", "positive affirmations",
            "gratitude practice", "breathing exercises", "progressive relaxation", "guided imagery",
        ];
        let clean_batches = 4;
        for b in 0..clean_batches {
            let chunk_start = b * (clean_topics.len() / clean_batches);
            let chunk_end = if b == clean_batches - 1 { clean_topics.len() } else { (b + 1) * (clean_topics.len() / clean_batches) };
            let chunk = &clean_topics[chunk_start..chunk_end];
            print!("    Batch {} ({}/{})...", b + 1, chunk.len(), clean_topics.len());
            let batch = generate_noise_batch(&*gen_client, &golden_session, chunk, false).await;
            let count = batch.len();
            all_noisy.extend(batch);
            println!(" ✓ ({})", count);
        }
        println!("  Clean sessions: {}", all_noisy.iter().filter(|s| !s.is_adversarial).count());
        println!("  Total noise sessions: {}", all_noisy.len());

        // ── Phase 4: Generate queries ──
        println!("\n  Phase 4: Generating queries (1 LLM call)...");
        let noise_topics: Vec<String> = all_noisy.iter().map(|s| s.topic.clone()).collect();
        let (pos_queries, neg_queries) = generate_queries(&*gen_client, &golden_session, &noise_topics).await;
        println!("  ✓ Positive queries: {}", pos_queries.len());
        println!("  ✓ Negative queries: {}", neg_queries.len());

        // ── Phase 5: Store everything ──
        println!(
            "\n  Phase 5: Storing {} sessions (1 golden + {} noise)...",
            1 + all_noisy.len(),
            all_noisy.len()
        );
        let temp_dir = TempDir::new().unwrap();
        let mgr = Arc::new(make_manager(&temp_dir, client).await);

        let golden_id = store_session(&mgr, &*gen_client, &golden_session).await;
        println!("  ✓ Golden session stored");

        for noisy in &all_noisy {
            let _ = store_session(&mgr, &*gen_client, &noisy.session).await;
        }
        mgr.refresh_layer_manifest().await.unwrap();
        let total = 1 + all_noisy.len();
        println!("  ✓ Total stored: {}", total);

        // ── Phase 6: Retrieval with K=5 ──
        let k = 5;
        println!(
            "\n  Phase 6: Retrieval (K={} out of {} memories, {:.1}% of corpus)",
            k, total, k as f64 / total as f64 * 100.0
        );

        // ── Positive queries ──
        println!("\n  ── Positive queries (golden fact MUST be found) ──");
        let mut pos_passed = 0usize;
        let mut pos_rank_sum = 0usize;

        for (i, query) in pos_queries.iter().enumerate() {
            let hits = mgr
                .search_with_threshold(query, &Filters::default(), k, Some(0.0))
                .await
                .unwrap_or_default();
            let golden_rank = hits.iter().position(|h| h.memory.id == golden_id);
            let qshort: String = query.chars().take(55).collect();

            match golden_rank {
                Some(rank) => {
                    let score = hits[rank].score;
                    println!(
                        "  ✓ {:2}. \"{}\" → rank {} [{:.3}]",
                        i + 1, qshort, rank + 1, score
                    );
                    pos_passed += 1;
                    pos_rank_sum += rank + 1;
                }
                None => {
                    println!(
                        "  ✗ {:2}. \"{}\" → NOT IN TOP {}",
                        i + 1, qshort, k
                    );
                    if !hits.is_empty() {
                        let preview: String = hits[0]
                            .memory
                            .content
                            .as_ref()
                            .map(|c| c.chars().take(80).collect())
                            .unwrap_or_default();
                        println!("       Top hit: {:.3} — {}", hits[0].score, preview);
                    }
                }
            }
        }

        let avg_pos_rank = if pos_passed > 0 {
            pos_rank_sum as f64 / pos_passed as f64
        } else {
            f64::MAX
        };

        // ── Negative queries ──
        println!("\n  ── Negative queries (golden fact must NOT be found) ──");
        let mut neg_passed = 0usize;

        for (i, query) in neg_queries.iter().enumerate() {
            let hits = mgr
                .search_with_threshold(query, &Filters::default(), k, Some(0.0))
                .await
                .unwrap_or_default();
            let golden_in_topk = hits.iter().any(|h| h.memory.id == golden_id);
            let qshort: String = query.chars().take(55).collect();

            if !golden_in_topk {
                neg_passed += 1;
                println!("  ✓ {:2}. \"{}\" → golden NOT found", i + 1, qshort);
            } else {
                let rank = hits.iter().position(|h| h.memory.id == golden_id).unwrap() + 1;
                println!(
                    "  ✗ {:2}. \"{}\" → golden incorrectly found at rank {}",
                    i + 1, qshort, rank
                );
            }
        }

        // ── Recall@K sweep ──
        println!("\n  ── Recall@K sweep (golden fact retrieval) ──");
        let sweep_ks = [1, 3, 5, 10, 20];
        for sweep_k in &sweep_ks {
            let mut found_at_k = 0usize;
            for query in &pos_queries {
                let hits = mgr
                    .search_with_threshold(query, &Filters::default(), *sweep_k, Some(0.0))
                    .await
                    .unwrap_or_default();
                if hits.iter().any(|h| h.memory.id == golden_id) {
                    found_at_k += 1;
                }
            }
            let recall = found_at_k as f64 / pos_queries.len() as f64 * 100.0;
            println!(
                "  Recall@{:2}: {}/{} ({:.0}%)",
                sweep_k, found_at_k, pos_queries.len(), recall
            );
        }

        // ── Summary ──
        let total_queries = pos_queries.len() + neg_queries.len();
        let total_passed = pos_passed + neg_passed;
        let adv_count = all_noisy.iter().filter(|s| s.is_adversarial).count();
        let clean_count = all_noisy.iter().filter(|s| !s.is_adversarial).count();

        let sep = "═".repeat(72);
        println!();
        println!("{}", sep);
        println!("  TOUGH RETRIEVAL — ALL LLM-GENERATED — SUMMARY");
        println!("{}", sep);
        println!(
            "  Corpus size:        {} memories (1 golden + {} noise)",
            total, all_noisy.len()
        );
        println!("  Adversarial noise:  {} (shares keywords with golden)", adv_count);
        println!("  Clean noise:        {} (completely unrelated)", clean_count);
        println!(
            "  Retrieval K:        {} ({:.1}% of corpus)",
            k,
            k as f64 / total as f64 * 100.0
        );
        println!(
            "  Positive:           {}/{} (avg rank {:.1})",
            pos_passed,
            pos_queries.len(),
            avg_pos_rank
        );
        println!(
            "  Negative:           {}/{} (golden correctly excluded)",
            neg_passed,
            neg_queries.len()
        );
        println!("  Total passed:       {}/{}", total_passed, total_queries);
        println!("  LLM calls:          ~8 (golden + 2 adv + 2 clean + queries)");
        println!("  Total time:         {:?}", start.elapsed());
        println!("{}", sep);

        // ── Assertions ──
        assert!(
            pos_passed >= pos_queries.len().saturating_sub(1),
            "Expected most positive queries to find golden fact: {}/{}",
            pos_passed,
            pos_queries.len()
        );
        assert!(
            neg_passed >= neg_queries.len().saturating_sub(1),
            "Expected most negative queries to NOT find golden fact: {}/{}",
            neg_passed,
            neg_queries.len()
        );

        println!("\n  ✓ Tough retrieval test passed");
    }
}
