[alias]
real-tests = "test --release --features local,vulkan --test functional_discovery real_pipeline"
tough-tests = "test --release --features local,vulkan --test tough_retrieval tough_pipeline -- --nocapture"
